  client.println("<html>");
  client.println("<head><title>Energia Ethernet Web Server</title></head>");
  client.println("<body align=center>");
  client.println("<h1 align=center><font color=\"red\">Welcome to the Ethernet Web Server</font></h1>");
  client.println("<form id=\"form1\" method=\"post\" action=\"/set1\">");
  client.println("    <button onclick=\"document.getElementById('form1').submit(); return false;\">set 1</button>");
  client.println("</form>");
  client.println("<form id=\"form0\" method=\"post\" action=\"/set0\">");
  client.println("    <button onclick=\"document.getElementById('form0').submit(); return false;\">set 0</button>");
  client.println("</form>");
  client.println("variable is " + variable + "<br>");
  client.println("<a href=\"/config.html\">refresh</a> <br>");
  client.println("<a href=\"/index.html\">home</a> <br>");
  client.println("</body>");
  client.println("</html>");
